title: Your awesome title
email: elisehein@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: "http://elisehe.in"
baseurl: ""
permalink: /blog/:year/:month/:day/:title/

# Allow future dates
future: true

markdown: kramdown

gems:
  - jekyll-gist
  - jekyll-paginate

# How many posts per page
paginate: 2
paginate_path: "/blog/:num/"
